#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = solaar
# exec-once = ags run
exec-once = qs -c widget
# exec-once = dunst
exec-once = /usr/lib/polkit-kde-authentication-agent-1

exec-once = swww-daemon &
# Set a wallpaper per monitor. Adjust image paths as needed.
exec-once = sleep 1 && swww img /home/luis/Imagens/wallpaper/leaves.jpg --outputs DP-1
exec-once = sleep 1 && swww img /home/luis/Imagens/wallpaper/Island05.png --outputs HDMI-A-1
exec-once = sleep 1 && swww img /home/luis/Imagens/wallpaper/Japanese-Red-Autumn.jpg --outputs HDMI-A-2

exec-once = hypridle

# cliphist
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data

# fix dolphin
exec-once = kbuildsycoca6

# Autostart programs on specific workspaces
exec-once = [workspace 1 silent] sh -c 'sleep 3 && spotify-launcher'
exec-once = [workspace 2 silent] sh -c 'sleep 3 && discord'
